stripe-samples/subscription-use-cases

usage-based-subscriptions/server/java/src/main/java/com/stripe/sample/ReportUsage.java
usage-based-subscriptions/server/node/reportUsage.js
usage-based-subscriptions/server/php/report_usage.php
usage-based-subscriptions/server/python/report_usage.py
usage-based-subscriptions/server/ruby/report_usage.rb

From the [docs](https://stripe.com/docs/api/usage_records/create?lang=php#usage_record_create-action):
> Valid values are increment (default) or set. When using `increment` the specified quantity will be added to the usage at the specified timestamp. **The `set` action will overwrite the usage quantity at that timestamp.** If the subscription has billing thresholds, increment is the only allowed value.

fix action as `set` for usage reporting in usage based sample

---

fixed-price-subscriptions/client/script.js
fixed-price-subscriptions/server/dotnet/Controllers/BillingController.cs
fixed-price-subscriptions/server/java/src/main/java/com/stripe/sample/Server.java
fixed-price-subscriptions/server/node/server.js
fixed-price-subscriptions/server/php/index.php
fixed-price-subscriptions/server/python/server.py
fixed-price-subscriptions/server/ruby/server.rb
per-seat-subscriptions/client/script.js
per-seat-subscriptions/server/java/src/main/java/com/stripe/sample/Server.java
per-seat-subscriptions/server/node/server.js
per-seat-subscriptions/server/php/index.php
per-seat-subscriptions/server/python/server.py
per-seat-subscriptions/server/ruby/server.rb
usage-based-subscriptions/client/script.js
usage-based-subscriptions/server/dotnet/Controllers/BillingController.cs
usage-based-subscriptions/server/java/src/main/java/com/stripe/sample/Server.java
usage-based-subscriptions/server/node/server.js
usage-based-subscriptions/server/php/index.php
usage-based-subscriptions/server/python/server.py
usage-based-subscriptions/server/ruby/server.rb

Change sample webhook references from `invoice.payment_succeeded` to `invoice.paid`

invoice.payment_succeeded → invoice.paid

---

README.md
usage-based-subscriptions/client/script.js
usage-based-subscriptions/server/dotnet/Controllers/BillingController.cs
usage-based-subscriptions/server/dotnet/dotnet.csproj
usage-based-subscriptions/server/go/server.go
usage-based-subscriptions/server/java/src/main/java/com/stripe/sample/Server.java
usage-based-subscriptions/server/node/server.js
usage-based-subscriptions/server/php/index.php
usage-based-subscriptions/server/python/server.py
usage-based-subscriptions/server/ruby/server.rb

Metered billing charges in arrears, this means a Setup Intent will be created instead of a Payment Intent at the time of subscription create.  Added support for handling Setup Intents with a status of 'requires_action' on the client and sending the customer through the authentication flow.  
Additionally fixed some display bugs where we weren't handling card decline errors.  
Upgraded the .NET lib as the older version is missing params required for clearing usage on an invoice item.

Add support for Setup Intents for metered billing

---

fixed-price-subscriptions/server/php/index.php

r? @thorsten-stripe 
It was pointing to the repo's static path structure, but not the stripe-cli generated one; now it uses the STATIC_DIR .env variable instead.

Fix PHP static dir path

---

fixed-price-subscriptions/client/react/src/PaymentForm.js

The call to `createSubscription()` , which is the the happy-path for `handleSubmit()` was nested in a 2nd level if-else.
This change flattens the code, and brings the happy-path to a top level function indentation.
[Reference](https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html)
cc @ctrudeau-stripe

Refactor handleSubmit() to use guard statements

---

usage-based-subscriptions/server/go/server.go

The golang sample on card decline fails without displaying anything because the returned object doesn't have an ```error``` field. This might occur elsewhere in the project. Usage-based is just where I encountered it. 🍻

Golang usage-based: display card decline error

---

fixed-price-subscriptions/server/node/server.js

The header being sent from the Stripe test harness has capitalised words

Fix expected header name

---

per-seat-subscriptions/client/script.js

I got the following error when I was trying the golang app:
web_1     | 2020/09/13 01:59:14 json.NewDecoder.Decode: json: cannot unmarshal string into Go struct field .quantity of type int64
It was because the script.js was sending the quantity as a string to /retrieve-upcoming-invoice like as follows.
```json
{"customerId":"cus_I0mDxZPTvsuAfK","subscriptionId":null,"newPriceId":"basic","quantity":"42"}
```

Treat the quantity as integer, not string

---

per-seat-subscriptions/server/ruby/Gemfile

I got the following error when I started the app and I added the gem to fix it.
```
web_1     | server.rb:5:in `require': cannot load such file -- sinatra/reloader (LoadError)                                                                                                                          
web_1     |     from server.rb:5:in `<main>'
```

Add sinatra-contrib to load sinatra/reloader

---

fixed-price-subscriptions/server/node/server.js

Hello. I've found the node example for fixed-price-subscriptions does not work due to StripeSignatureVerificationError and fixed it.
According to #48, it seems `req.headers` returns different values depending on its running environment (I haven't investigated it). In my environment, `req.headers` returns headers with lower-cased keys. However, HTTP headers are case-insensitive and applications should not care letter cases. To that end, we can get header values with [`req.header(field)`](https://expressjs.com/en/api.html#req.get) instead of directly referencing the object.
* Stripe CLI version: 1.5.1
* Node.js version: v10.7.0
* NPM version: 6.1.0
<details>
<summary>NPM packages</summary>
<pre>
subscriptions-with-fixed-prices@1.0.0 /app/server/node
+-- @fullhuman/postcss-purgecss@2.3.0
| …

Use req.header(field) to fix signature verification failure on the node example

---

fixed-price-subscriptions/server/python/requirements.txt
per-seat-subscriptions/server/python/requirements.txt
usage-based-subscriptions/server/python/requirements.txt

When I tried Python examples with Python 3.8.5, I got the following error:
TypeError: required field "type_ignores" missing from Module
I updated the dependency since it seems the error is related to this issue:
https://github.com/pallets/werkzeug/issues/1551

Use Werkzeug 0.15.5 or newer to fix TypeError

---

fixed-price-subscriptions/server/php/composer.json
usage-based-subscriptions/server/php/composer.json

Running `composer install` on a freshly downloaded copy of `fixed-price-subscriptions` gets you the error:
```
[Composer\Json\JsonValidationException]
"./composer.json" does not match the expected JSON schema:
- name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$
```
This is because composer now requires you have a very [specific naming scheme](https://getcomposer.org/doc/04-schema.md#name) in composer.json files. This PR fixes the "name" property for fixed-price and metered-usage samples. Per-seat already had the correct naming scheme.

Fixed composer json

---

.github/workflows/ci.yml
fixed-price-subscriptions/server/java/README.md
fixed-price-subscriptions/server/java/pom.xml
per-seat-subscriptions/server/java/README.md
per-seat-subscriptions/server/java/pom.xml
usage-based-subscriptions/server/java/README.md
usage-based-subscriptions/server/java/pom.xml

As described in https://github.com/stripe-samples/sample-ci/pull/2, I changed the jar file names to the same one.

Use the same name to let CI run without passing the jar file path

---

.github/workflows/ci.yml
.gitignore

By this jobs on ci.yml can be run on local machines with `act`.
Related to stripe-samples/sample-ci#6, same as stripe-samples/checkout-single-subscription#58

Make ci.yml compatible with `act`

---

.github/workflows/ci.yml

@cjavilla-stripe If the PR https://github.com/stripe-samples/sample-ci/pull/10 sounds good, I'd like to request reviewing this, too. By the change on sample-ci, the sample repository code will be copied to the containers earlier than before. I moved `rm -rf ...` to the very first step so it keeps its effect.

Remove dotnet/ReportUsage in advance to support the new changes on sample-ci

---

usage-based-subscriptions/server/python/requirements.txt

Fixes: https://github.com/stripe-samples/subscription-use-cases/runs/2879167445
I fixed a dependency conflict for `usage-based-subscriptions/server/python` by updating `requests` and `stripe` to the same versions as fixed-price-subscriptions.
I assume the CI started failing when the pip in the `python:3.8` was updated. I couldn't reproduce this error with an older pip (20.2.4) but could with a newer one (21.1.2).

Fix dependency conflict

---

.github/workflows/ci.yml
.gitignore
Gemfile
fixed-price-subscriptions/client/react/src/Register.js
spec/capybara_support.rb
spec/fixed_price_e2e_spec.rb
spec/spec_helper.rb

Hello. I added e2e tests for fixed-price-subscriptions samples. This runs the same tests for `client/vanillajs` and `client/react`.

Add e2e tests for fixed-price-subscriptions

---

fixed-price-subscriptions/client/vanillajs/prices.js

When calling the `/create-subscription` API from the vanilla JS example, we set the customer ID into the request body.
https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/client/vanillajs/prices.js#L47
But the server application does not use this props. They get it from Cookie.
https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/php-slim/index.php#L99
https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/node/server.js#L92
https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/ruby/server.rb#L72
https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/dotnet/Co …

chore: remove unused customer ID value

---

fixed-price-subscriptions/client/vanillajs/prices.js
fixed-price-subscriptions/client/vanillajs/subscribe.js

Ref: #179
Set the response of `/create-customer` API value into localStorage instead of URLSearchParams.

Replace the handler of the clientSecret from URLSearchParams to  localStorage

---

.github/workflows/ci.yml
fixed-price-subscriptions/server/node/server.js
fixed-price-subscriptions/server/php-slim/composer.json
fixed-price-subscriptions/server/php-slim/index.php

Hi. I made a couple of changes to fix errors on CI.
* Updated the Docker images.
* Updated PHP Slim from 3 to 4 because it seems 3 does not support the latest PHP.
* Added error handlings to webhook endpoints: when an `invoice.payment_succeeded` event arrived after the subscription cancellation, the StripeInvalidRequestError would occur while updating the subscription. I guess the other implementations might have the same problem, too (I applied this only for node and php-slim implementations for now).
See also: https://www.slimframework.com/docs/v4/start/upgrade.html

Update images and Slim framework, error handlings for webhook endpoints

---

.github/dependabot.yml

To make maintainability of the samples easier, I'm specifying which day Dependabot should open PRs so we can try to focus our effort on a single day.

Update dependabot day to thursday

---

.github/dependabot.yml
.github/workflows/automerge.yml

This PR is adding an action to auto-merge dependabot PRs when the packages updated are Stripe SDKs. To test this, I am starting with the Stripe Java SDK. If it works as expected, I'll open another PR to add the other SDKs.

Start adding automerge action for Stripe SDKs updates

---

.github/workflows/ci.yml

Hi. I updated the `ci.yml` to reflect the version that the current .Net samples support.
A couple of tests for per-seat-subscription samples in Java are also failing. I'd be happy to fix this if these samples are still needed (related: https://github.com/stripe-samples/subscription-use-cases/pull/354).

The samples now only support .NET 6.0

---

fixed-price-subscriptions/server/node/server.js
fixed-price-subscriptions/server/php-slim/index.php
fixed-price-subscriptions/server/python/server.py
fixed-price-subscriptions/server/ruby/config_helper.rb
fixed-price-subscriptions/server/ruby/server.rb
spec/spec_helper.rb
usage-based-subscriptions/server/node/server.js
usage-based-subscriptions/server/php/index.php
usage-based-subscriptions/server/python/server.py
usage-based-subscriptions/server/ruby/server.rb

Hi, I made a couple of changes to fix failing tests on CI.
1. Update Stripe API versions (57661e3b928db7f16aaff6703f37982ec35d8358): Some samples implemented in static-typed languages have been failing ([example](https://github.com/stripe-samples/subscription-use-cases/actions/runs/3702480622/jobs/6272807682#step:6:102)) since the specified API version was not the expected one. I updated each version to `2022-08-01` from `2020-08-27`.
2. File.exists? had been deprecated and removed from Ruby 3.1 (3cd67197d0ee4ea5bc750df47886a2afa3cdc718): updated to File.exist?
3. Stripe::Subscription.delete has been removed on 8.0.0 (6e4a7e8dc1b438b44cf88ad53943f20189b66fdc): stripe-ruby have some API changes on 8.0.0, updated.

Fix failing tests

---

.github/workflows/ci.yml

Updated the [actions/checkout](https://github.com/actions/checkout) to v3 since v2 has been causing the deprecation warning like this:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Update actions/checkout to the latest version

---

.gitignore

Sometimes we accidentally add the `sample-ci` directory in our local development.
Therefore, we will add the `sample-ci` directory to our .gitignore file to intentionally ignore it in our git repository.
@hibariya How do you think this update?
If this update will break our CI workflow, please let me know.

chore: ignore sample-ci dir for CI testing

---

fixed-price-subscriptions/client/react/package.json

Related: #730 
We will temporarily exclude `react-router-dom` from the major update targets since it requires addressing breaking changes:
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-router-dom.js?v=341d8557' does not provide an export named 'withRouter' 
```
After this update, we will separately undertake the major update adjustments.

chore: upgrade react and related library

---

fixed-price-subscriptions/server/node/server.js

Fixes a typo in the node server example's console output.

fix typo in server.js

---

fixed-price-subscriptions/client/react/package.json
fixed-price-subscriptions/client/react/src/Account.jsx
fixed-price-subscriptions/client/react/src/App.jsx
fixed-price-subscriptions/client/react/src/Cancel.jsx
fixed-price-subscriptions/client/react/src/Prices.jsx
fixed-price-subscriptions/client/react/src/Register.jsx
fixed-price-subscriptions/client/react/src/Subscribe.jsx

Continue task of #958
`react-router-dom` had a breaking change between v5 to v6.
https://reactrouter.com/en/main/upgrading/v5
To address this, we updated React application code to fix errors that come from this package upgrade.

Replacing the v5 react-router-dom component to v6

---

.github/workflows/ci_e2e.yaml
.github/workflows/server_test.yaml

Github deprecated `docker-compose`: https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/

CI: move to `docker compose`

---

.github/workflows/ci_dotnet.yaml
.github/workflows/ci_e2e.yaml
.github/workflows/ci_go.yaml
.github/workflows/ci_java.yaml
.github/workflows/ci_node.yaml
.github/workflows/ci_php.yaml
.github/workflows/ci_python.yaml
.github/workflows/ci_ruby.yaml

This PR removes the `pull_request_target` from the GitHub Action workflow triggers.
Right now, by using `pull_request_target`, the workflow executes off the targeted branch. That is, if we got a PR that's trying to merge code into `main`, then the CI tests would actually run off the existing `main` branch, which isn't what we want!
But we also can't easily use a different trigger like `pull_request`. The issue is that these CI checks are meant to run end-to-end tests, making live requests using a dedicated Stripe test account. And secrets (reasonably!) aren't available to pull requests from forked repositories.
In terms of benefit/risks tradeoffs, we decided that the preferred option is to just run these tests on pushes to the main branch. We have this today, so the only change to make …

Change CI workflow triggers to pull_request
