client/script.js

Because of [this](https://github.com/stripe-samples/subscription-with-fixed-price/blob/master/client/script.js#L102-L103).

Pass the correct argument to the displayError function

---

README.md

Got a ping on Twitter these were broken :)
r? @ctrudeau-stripe 
cc @stripe/samples

Update links in readme to correct sandbox

---

usage-based-subscriptions/server/java/src/main/java/com/stripe/sample/ReportUsage.java
usage-based-subscriptions/server/node/reportUsage.js
usage-based-subscriptions/server/php/report_usage.php
usage-based-subscriptions/server/python/report_usage.py
usage-based-subscriptions/server/ruby/report_usage.rb

Syncs up some changes made on the docs side for the printed output.

Update printed text

---

usage-based-subscriptions/client/script.js

The stated  price and amount don't match. This fixes this.

updated amount to equal stated price

---

per-seat-subscriptions/client/css/global.css
per-seat-subscriptions/client/css/index.css
per-seat-subscriptions/client/prices.html
per-seat-subscriptions/client/script.js
per-seat-subscriptions/server/node/tailwind.config.js

- Adding UI tweaks. 
- Adding new CSS

Tweaking UI for per seat guide

---

per-seat-subscriptions/README.md
per-seat-subscriptions/server/java/src/main/java/com/stripe/sample/Server.java
per-seat-subscriptions/server/node/server.js
per-seat-subscriptions/server/php/index.php
per-seat-subscriptions/server/ruby/server.rb
spec/per_seat_server_spec.rb
spec/spec_helper.rb

went through various server integrations to make sure they were passing the tests. Small fixes across the board, primarily in support of using test tokens. Minor text fixes as I found them.

get tests working across servers

---

fixed-price-subscriptions/server/dotnet/README.md
per-seat-subscriptions/server/dotnet/Controllers/BillingController.cs
per-seat-subscriptions/server/dotnet/README.md
per-seat-subscriptions/server/go/README.md
per-seat-subscriptions/server/go/server.go
per-seat-subscriptions/server/node/server.js
spec/spec_helper.rb
usage-based-subscriptions/server/dotnet/README.md

fixed 
- bug in tests in how we were passing arguments to POST calls
- bad var name in node create sub call. 
- missing quantity param in Go server 
Added README.mds for server dirs missing them.  
Changed error status codes to be 400 across the board for consistency with tests for right now (with a nod to going back to more specific errors down the road).

various bug fixes

---

fixed-price-subscriptions/server/php/index.php
per-seat-subscriptions/server/php/index.php
usage-based-subscriptions/server/php/index.php

Use static method for constructing webhook events

---

fixed-price-subscriptions/server/node/server.js
per-seat-subscriptions/server/node/server.js
usage-based-subscriptions/server/node/server.js

Fix env reference for helper error closes #43

---

fixed-price-subscriptions/server/python/server.py

changed multiple if checks to elif since only comparing one variable (event_type)

changed multiple if checks to elif

---

fixed-price-subscriptions/package.json
per-seat-subscriptions/package.json
per-seat-subscriptions/server/node/package.json
usage-based-subscriptions/package.json

update package.json in  use case subdir level package.json to be inline with the corresponding /server/node/package.json.  The higher level one is used by codesandbox atm for deployment, this is a quick fix for getting those deploys up and running until we can do something better, perhaps using the codesandbox API to help with deployment.

update package.json files in use case directories

---

fixed-price-subscriptions/package.json

fix use case directory level package.json so that the node server can be started outside of the server/node path, this is to support codesandbox deploys.

fix paths in package.json for server and react client

---

fixed-price-subscriptions/server/node/package.json
fixed-price-subscriptions/server/node/server.js

Remove yarn and post css dependencies.

Add error handling for node calls

---

fixed-price-subscriptions/server/php-slim/index.php

Migrate php to use default incomplete for subscriptions

---

fixed-price-subscriptions/client/react/src/Account.js
fixed-price-subscriptions/client/react/src/App.css
fixed-price-subscriptions/client/react/src/Prices.js
fixed-price-subscriptions/client/react/src/Subscribe.js
fixed-price-subscriptions/client/react/src/index.js
fixed-price-subscriptions/client/vanillajs/account.js
fixed-price-subscriptions/client/vanillajs/prices.html
fixed-price-subscriptions/client/vanillajs/prices.js
fixed-price-subscriptions/client/vanillajs/subscribe.html
fixed-price-subscriptions/client/vanillajs/subscribe.js
fixed-price-subscriptions/seed.json
fixed-price-subscriptions/server/dotnet/Controllers/BillingController.cs
fixed-price-subscriptions/server/dotnet/Models/ConfigResponse.cs
fixed-price-subscriptions/server/dotnet/Models/CreateSubscriptionRequest.cs
fixed-price-subscriptions/server/dotnet/Models/SubscriptionCreateResponse.cs
fixed-price-subscriptions/server/go/server.go
fixed-price-subscriptions/server/java/src/main/java/com/stripe/sample/Server.java
fixed-price-subscriptions/server/node/package.json
fixed-price-subscriptions/server/node/server.js
fixed-price-subscriptions/server/php-slim/index.php
fixed-price-subscriptions/server/python/requirements.txt
fixed-price-subscriptions/server/python/server.py
fixed-price-subscriptions/server/ruby/server.rb
spec/fixed_price_server_spec.rb
spec/spec_helper.rb

Update vanilla JS and Ruby server to use `default_incomplete` to create and pay for a subscription.

Migrate to default incomplete

---

.github/workflows/ci.yml
fixed-price-subscriptions/server/dotnet/dotnet.csproj
usage-based-subscriptions/server/dotnet/dotnet.csproj

Hello. Like as https://github.com/stripe-samples/accept-a-payment/pull/192,  made it run with multiple runtimes.
Here's the result of the CI run on my fork: https://github.com/hibariya/subscription-use-cases/actions/runs/1140971319

Run server tests with multiple runtimes

---

per-seat-subscriptions/server/java/src/main/java/com/stripe/sample/Server.java

Only the last InvoiceLineItem on the invoice was getting dded to the nextInvoiceSum total.

Fix upcoming invoice logic

---

per-seat-subscriptions/README.md

This readme seemed to be a copy of the fixed-subscription example

Fix some README sections

---

fixed-price-subscriptions/server/go/server.go

leave to use %s format in Println (Go)

removed unused %s in Go

---

per-seat-subscriptions/server/go/server.go

There was a problem in per-seat-subscriptions

fixed to respond current quantity in Go

---

README.md

Chore: Add the lists of contributors on README.md

---

.github/workflows/ci_dotnet.yaml
.github/workflows/ci_e2e.yaml
.github/workflows/ci_go.yaml
.github/workflows/ci_java.yaml
.github/workflows/ci_node.yaml
.github/workflows/ci_php.yaml
.github/workflows/ci_python.yaml
.github/workflows/ci_ruby.yaml

Reverts stripe-samples/subscription-use-cases#1144

Revert "update gh action trigger"
